### ISSUE TITLE
[Bug] expected type of string but got null

### ISSUE THREAD

**Issue by moritzjacobs** [kodingdotninja/create-chakra-icons#7]
Hi! Great project, but I have trouble converting some files.

### Minimal reproduction

**CLI:**

```
> npx create-chakra-icons -o Icons.js ./check.svg

Property value expected type of string but got null
✖  Error building interactive interface
```

**SVG:**

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 67 67">
  <g fill="none" stroke="#000">
    <path d="m18.951 33.437 9.95 9.951L48.36 23.929"/>
    <circle cx="33.5" cy="33.5" r="33.5" stroke="none"/>
    <circle cx="33.5" cy="33.5" r="33"/>
  </g>
</svg>

```

**Env.:** node v14.17.6 @ macOS 11.6

Thanks for your help!

**Comment by ri7nz** [comment]
Thanks for you contribution, have been fix in #8 (you can use the next version)

**Comment by moritzjacobs** [comment]
Great work, thanks!

**Comment by ri7nz** [comment]
@moritzjacobs  You can use the latest version 

Here's an example 

![image](https://user-images.githubusercontent.com/16365952/141969503-602916cb-7bb1-4ed8-8d94-9de56f6fc689.png)

**Comment by moritzjacobs** [comment]
Works like a charm, thank you!

**Comment by ri7nz** [comment]
Thank you @moritzjacobs
